version: "3.7"

services:
  mongo:
    container_name: grpc-mongo
    image: mongo:4
    restart: unless-stopped
    ports:
      - 27017:27017
    volumes: 
      - ./volumes/mongodb:/data/db
      - ./volumes/mongodb_config:/data/configdb
